In [1]:
from scipy.stats import randint, uniform

In [2]:
ri = randint(0, 10) # 0~9 무작위 수
ri.rvs(11) # 0~9사이 숫자 중 무작위 수를 11개 생성

array([3, 4, 8, 0, 3, 7, 9, 3, 6, 5, 8])

In [4]:
import numpy as np
np.unique(ri.rvs(1000), return_counts=True) # 중복된 총 갯수를 함께 반환

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 89,  93,  95, 111,  96, 104, 111,  92, 103, 106]))

In [5]:
ui = uniform(0,1) # 0~1 사이의 무작위 실수
ui.rvs(5) # 0~1 사이 무작위 실수를 5개 생성

array([0.92647296, 0.88762704, 0.41183616, 0.77595825, 0.61412793])