In [23]:
import keras

(train_input, train_target), (test_input, test_target) =\
      keras.datasets.fashion_mnist.load_data()

In [24]:
#정규화, 0~1
train_scaled = train_input / 255.0
train_scaled = train_scaled.reshape(-1, 28 * 28)

In [25]:
# 훈련세트, 검증 세트
from sklearn.model_selection import train_test_split
train_scaled, val_scaled, train_target, val_target = train_test_split(
    train_scaled, train_target, test_size=0.2, random_state=42
)

In [ ]:
# # 입력층, 밀집층, 출력층
# inputs = keras.layers.Input(shape=(784,))
# #dense1 = keras.layers.Dense(100, activation='sigmoid')
# #dense2 = keras.layers.Dense(50, activation='sigmoid')
# dense1 = keras.layers.Dense(100, activation='relu')
# dense2 = keras.layers.Dense(50, activation='relu')
# output = keras.layers.Dense(10, activation='softmax')

# model = keras.Sequential([inputs, dense1, dense2, output])

In [30]:
model = keras.Sequential()
model.add(keras.layers.Input(shape=(784,)))
model.add(keras.layers.Dense(100, activation='relu'))
model.add(keras.layers.Dense(50, activation='relu'))
model.add(keras.layers.Dense(10, activation='softmax'))

In [31]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                │ (None, 100)            │        78,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 50)             │         5,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 10)             │           510 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 84,060 (328.36 KB)

 Trainable params: 84,060 (328.36 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [33]:
model.fit(train_scaled, train_target, epochs=5)

Epoch 1/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7573 - loss: 0.6915
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8558 - loss: 0.3999
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8694 - loss: 0.3597
Epoch 4/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8796 - loss: 0.3326
Epoch 5/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8855 - loss: 0.3192


In [34]:
# 모델 평가
test_scaled = test_input / 255.0
test_scaled = test_scaled.reshape(-1, 28 * 28)
model.evaluate(test_scaled, test_target)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.8626 - loss: 0.3950


[0.3992951214313507, 0.8618000149726868]

In [ ]:
# 예측하기
import numpy as np
predictions = model.predict(test_scaled[:10]) 
print(np.round(predictions, decimals=3))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
[[0.    0.    0.    0.    0.    0.007 0.    0.002 0.    0.992]
 [0.    0.    0.997 0.    0.001 0.    0.002 0.    0.    0.   ]
 [0.    1.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    1.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.125 0.    0.028 0.003 0.002 0.    0.842 0.    0.    0.   ]
 [0.    1.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    1.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.014 0.    0.985 0.    0.    0.   ]
 [0.    0.    0.    0.    0.    1.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.002 0.    0.997 0.    0.001]]


In [39]:
np.argmax(predictions, axis=1)

array([9, 2, 1, 1, 6, 1, 4, 6, 5, 7])

In [40]:
# Flatten() 층, 다차원 넘파이 배열 -> 1차원적인 입력으로 변환
train_scaled = train_input / 255.0
train_scaled.shape

(60000, 28, 28)